### ISSUE TITLE
Need to trim table before parsing it

### ISSUE THREAD

**Issue by icetbr** [dborysov/md-table#4]
Hi there, you need to `trim()` your data, or else it will create an empty element at the end.

```js
    return data
        .split(/\r?\n/)
        .filter((row) => row)
        .map((row) => row
```

**Comment by dborysov** [comment]
Hi @icetbr!

Good point, thanks! [Added](https://github.com/dborysov/md-table/commit/d5689e9bf00ab715617884cc773ee783a4ff8bbf) `.trim()` and released in version 1.0.8
