### ISSUE TITLE
esm error: "self" is not defined

### ISSUE THREAD

**Issue by icetbr** [dborysov/md-table#6]
Hi there, I tried 1.0.12 (from 1.0.8) and the package seems to be bugged. I'm using node 19.4, and first I got an error saying I was using a named import and this only works for an esm module.

When I fixed this, I got "self" is not defined, in main.js. (don't have the stack right now)

**Comment by dborysov** [comment]
Thanks @icetbr 🙏🏻!

Fixed in 1.0.13. Could you verify?

**Comment by icetbr** [comment]
It does, thanks. it still might be a good idea to publish both esm and common versions. I mean, if you're willing to do the extra effort. I know that `rollup` does this nicely. I haven't got any examples of mine or else i would have made a PR or something.

This is how I have to use without the esm version:
```js
import MdTable from '@dborysov/md-table';
const { parseTable }  = MdTable;
```

**Comment by dborysov** [comment]
@icetbr, Thanks again,

in `1.0.15` now I'm exporting both commonjs & esm
